<a href="https://colab.research.google.com/github/lkostenko/ds_homeworks/blob/main/Kostenko_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [33]:
import numpy as np
import random

In [34]:
matrix = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])

In [35]:
vector = np.array([random.uniform(0, 1) for _ in range(10)])

In [36]:
matrix, vector

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 array([0.10996144, 0.32860804, 0.04075774, 0.07059401, 0.76739536,
        0.16282045, 0.22057686, 0.34634033, 0.52478015, 0.19076938]))

In [37]:
matrix.shape, vector.shape

((3, 3), (10,))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [38]:
vector_plus_10 = np.round((vector + 10), 2)

In [39]:
vector_plus_10

array([10.11, 10.33, 10.04, 10.07, 10.77, 10.16, 10.22, 10.35, 10.52,
       10.19])

In [40]:
vector_mult = np.dot(vector_plus_10 , 2)

In [41]:
vector_mult

array([20.22, 20.66, 20.08, 20.14, 21.54, 20.32, 20.44, 20.7 , 21.04,
       20.38])

In [42]:
vector_plus_10*2

array([20.22, 20.66, 20.08, 20.14, 21.54, 20.32, 20.44, 20.7 , 21.04,
       20.38])

In [43]:
vector_sqr = np.square(vector)

In [44]:
vector_sqr

array([0.01209152, 0.10798324, 0.00166119, 0.00498351, 0.58889564,
       0.0265105 , 0.04865415, 0.11995163, 0.27539421, 0.03639296])

In [45]:
vector ** 2

array([0.01209152, 0.10798324, 0.00166119, 0.00498351, 0.58889564,
       0.0265105 , 0.04865415, 0.11995163, 0.27539421, 0.03639296])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [46]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [47]:
result_matrix = np.dot(B, A)

In [48]:
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [49]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [50]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [51]:
result_matrix_T = result_matrix.T

In [52]:
result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [53]:
vector.T

array([0.10996144, 0.32860804, 0.04075774, 0.07059401, 0.76739536,
       0.16282045, 0.22057686, 0.34634033, 0.52478015, 0.19076938])

In [54]:
column_vector = np.expand_dims(vector, 1)
column_vector

array([[0.10996144],
       [0.32860804],
       [0.04075774],
       [0.07059401],
       [0.76739536],
       [0.16282045],
       [0.22057686],
       [0.34634033],
       [0.52478015],
       [0.19076938]])

In [55]:
vector

array([0.10996144, 0.32860804, 0.04075774, 0.07059401, 0.76739536,
       0.16282045, 0.22057686, 0.34634033, 0.52478015, 0.19076938])

In [57]:
column_vector.shape, vector.shape

((10, 1), (10,))

In [58]:
column_vector.T

array([[0.10996144, 0.32860804, 0.04075774, 0.07059401, 0.76739536,
        0.16282045, 0.22057686, 0.34634033, 0.52478015, 0.19076938]])

In [59]:
column_vector.T.shape

(1, 10)